version: "3.8"
services:
  db:
    image: mysql:latest
    container_name: example-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: example
      MYSQL_USER: example
      MYSQL_PASSWORD: example
    ports:
      - "13306:3306"
